version: "3.4"

services:
  eshopwebmvc:
    image: ${DOCKER_REGISTRY-}eshopwebmvc
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    environment:
      - Database__Provider=SqlServer
      - ConnectionStrings__CatalogConnection=Server=sql-server;Database=Microsoft.eShopOnWeb.CatalogDb;User Id=sa;Password=Pass@word
      - ConnectionStrings__IdentityConnection=Server=sql-server;Database=Microsoft.eShopOnWeb.Identity;User Id=sa;Password=Pass@word
    ports:
      - "8090:80"
    depends_on:
      - sql-server

  sql-server:
    image: mcr.microsoft.com/mssql/server:2017-CU14-ubuntu
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
